CRWBookStore/Models/Cart.cs
using CRWBookStore.Models;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace CRWBookStore.Models
{
    public class Cart
    {
        public List<CartLine> Lines { get; set; } = new List<CartLine>();
        public virtual void AddItem(BookModel book, int quantity)
        {
            CartLine line = Lines
            .Where(p => p.book.Book_id == book.Book_id)
            .FirstOrDefault();
            if (line == null)
            {
                Lines.Add(new CartLine
                {
                    book = book,
                    Quantity = quantity
                });
            }
            else
            {
                line.Quantity += quantity;
            }
        }
        public virtual void RemoveLine(BookModel book) =>
        Lines.RemoveAll(l => l.book.Book_id == book.Book_id);
        public decimal ComputeTotalValue() =>
        Lines.Sum(e => e.book.price * e.Quantity);

        public virtual void Clear() => Lines.Clear();

    }

    public class CartLine
    {
        [Key]
        public int customer_id { get; set; }
        public BookModel book { get; set; }
        public int Quantity { get; set; }


    }

}

CRWBookStore/Controllers/CartController.cs
using CRWBookStore.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CRWBookStore.Controllers
{
    public class CartController : Controller
    {
        private readonly DataContext _db;
        public CartController(DataContext db)
        {
            _db = db;
        }
        /*public async Task<IActionResult> addToCart(int customer_id,int book_id,int count)
        {
            customer_id.
        }*/
    }
}

CRWBookStore/Controllers/InventoryController.cs
using Microsoft.AspNetCore.Mvc;
using CRWBookStore.Data;
using CRWBookStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace CRWBookStore.Controllers
{
    public class InventoryController : Controller
    {
        private readonly DataContext _db;

        public InventoryController(DataContext db)
        {
            _db = db;
        }
        public IActionResult BrowseBooks()
        {
            var displayData = _db.Book.ToList();
            return View("BrowseBooks",displayData);
        }
        public IActionResult Login()
        {
            return View();
        }

        public IActionResult ThankYou()
        {
            return View();
        }
        [HttpPost]

        public async Task<IActionResult> Login(int Customer_id)
        {
            if (ModelState.IsValid)
            {
                _db.Add(Customer_id);
                await _db.SaveChangesAsync();
                return RedirectToAction("ContactInfo");
            }
            return View(Customer_id);
        }

       

    }
}

CRWBookStore/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using CRWBookStore.Models;
using System.Linq;
namespace CRWBookStore.Controllers
{
    public class OrderController : Controller
    {
        private IOrderRepository repository;
        private Cart cart;

        public OrderController(IOrderRepository repoService, Cart cartService)
        {
            repository = repoService;
            cart = cartService;
        }

        public ViewResult Checkout() => View(new Order());

        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }
            if (ModelState.IsValid)
            {
                order.Lines = cart.Lines.ToArray();
                cart.Clear();
                return RedirectToPage("/ThankYou", new { orderId = order.OrderID });
            }
            else
            {
                return View();
            }
        }
        public IActionResult PaymentInfo()
        {
            return View();
        }

    }
}

CRWBookStore/Pages/Cart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using CRWBookStore.Infrastructure;
using CRWBookStore.Models;
using System.Linq;

namespace CRWBookStore.Pages
{
    public class CartModel : PageModel
    {
        private IStoreRepository repository;
        public CartModel(IStoreRepository repo, Cart cartService)
        {
            repository = repo;
            Cart = cartService;
        }
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";

        }
        public IActionResult OnPost(long productId, string returnUrl)
        {
            BookModel book = repository.Books
                .FirstOrDefault(p => p.Book_id == productId);

            Cart.AddItem(book, 1);

            return RedirectToPage(new { returnUrl = returnUrl });
        }

        public IActionResult OnPostRemove(long productId, string returnUrl)
        {
            Cart.RemoveLine(Cart.Lines.First(cl =>
            cl.book.Book_id == productId).book);
            return RedirectToPage(new { returnUrl = returnUrl });
        }
    }
}

CRWBookStore/Pages/_CartLayout.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CRWBookStore.Pages
{
    public class _CartLayoutModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

CRWBookStore/Pages/_ViewImports.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CRWBookStore.Pages
{
    public class ViewImportsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

CRWBookStore/Pages/_ViewStart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CRWBookStore.Pages
{
    public class _ViewStartModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

CRWBookStore/Pages/Cart.cshtml
@page
@using CRWBookStore.Models
@using CRWBookStore.Pages
@model CartModel

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] CRW BOOK STORE</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="icon" href="favicon.ico"/>

</head>


<h5>Your Shopping Cart</h5>
<table class="table table-bordered table-striped">
     <thead>
         <tr>
             <th>Quantity</th>
             <th>Item</th>
             <th class="text-right">Price</th>
             <th class="text-right">Subtotal</th>
         </tr>
     </thead>
     <tbody>
         @foreach (var line in Model.Cart.Lines) {
         <tr>
             <td class="text-center">@line.Quantity</td>
             <td class="text-left">@line.book.Title</td>
            <td class="text-right">@line.book.price.ToString("c")</td>
             <td class="text-right">
             @((line.Quantity *line.book.price).ToString("c"))
             </td>
             <td class="text-center">
                    <form asp-page-handler="Remove" method="post">
                        <input type="hidden" name="productId"
                               value="@line.book.Book_id" />
                        <input type="hidden" name="returnUrl"
                               value="@Model.ReturnUrl" />
                        <button type="submit" class="btn btn-sm btn-danger">
                            Remove
                        </button>
                    </form>
                </td>
        </tr>
         }
     </tbody>
     <tfoot>
     <tr>
     <td colspan="3" class="text-right">Total:</td>

     <td class="text-right">
         @Model.Cart.ComputeTotalValue().ToString("c")
     </td>

     </tr>
     </tfoot>
</table>
<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue shopping</a>
    <a class="btn btn-primary" asp-action="PaymentInfo" asp-controller="Order">
        Checkout
    </a>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

CRWBookStore/Pages/_CartLayout.cshtml
@{
    ViewData["Title"] = "ShoppingCart-";
}
<!DOCTYPE html>
<html>
<head>
 <meta name="viewport" content="width=device-width" />
 <title>Shopping Cart-CRW BOOKSTORE</title>
 <link href="/lib/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />
 <link href="/lib/font-awesome/css/all.min.css" rel="stylesheet" />
 <link rel="icon" href="favicon.ico"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" ><strong>CRW BOOKSTORE</strong></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                       <!-- <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        -->
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Inventory" asp-action="BrowseBooks" >BOOK</a>
                        </li>
                        
                    </ul>
                </div>
                <partial name = "_loginPartial"/>
            </div>
            
        </nav>
    </header>

     <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>