CRWBookStore/Controllers/PDFController.cs
using Microsoft.AspNetCore.Mvc;
using CRWBookStore.Data;
using CRWBookStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace CRWBookStore.Controllers
{
    public class PDFController : Controller
    {
        private readonly DataContext _db;

        public PDFController(DataContext db)
        {
            _db = db;
        }
        public IActionResult BrowsePDF()
        {
            var displayData = _db.PDFs.ToList();
            return View("BrowsePDF", displayData);
        }
        public IActionResult Login()
        {
            return View();
        }

        public IActionResult ThankYou()
        {
            return View();
        }
        [HttpPost]


        public async Task<IActionResult> Login(int Customer_id)
        {
            if (ModelState.IsValid)
            {
                _db.Add(Customer_id);
                await _db.SaveChangesAsync();
                return RedirectToAction("ContactInfo");
            }
            return View(Customer_id);
        }



    }
}

CRWBookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] CRW BOOK STORE</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />  
    <link rel="icon" href="~/favicon.ico" />  

</head>
<body>

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><strong>CRW BOOKSTORE</strong></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                       <!-- <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        -->
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Inventory" asp-action="BrowseBooks">BOOK</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PDF" asp-action="BrowsePDF">PDFs</a>
                        </li>
                                               
                    </ul>
                </div>

                   <div class = "navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse" style = "margin-left:50%;">
                    <ul class="navbar-nav flex-grow-1">                            
                            <li class="nav-item">
                                <a href="/Cart?returnUrl=%2FInventory%2FBrowseBooks" class="nav-link text-dark"  >Cart</a>
                            </li>
                            <div class="col-6 text-right">
                                <vc:cart-summary />
                                
                            </div>
                    </ul>
                    </div>
                <partial name = "_loginPartial"/>                
            </div>
        </nav>
    </header>

    <div class="container mt-3 mb-3">

        @RenderBody()

    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>